name: Unit-Test pipeline and publish results

on:
  workflow_dispatch:   # manual run
  pull_request:        # auto run only on PRs into main
    branches:
      - main

jobs:
  unit-tests-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and generate JUnit XML
        run: |
          pytest --junitxml=report.xml || true

      - name: Parse test results
        id: parse
        run: python scripts/parse_test_results.py

      - name: Show Slack message (debug)
        run: cat slack_msg.txt

      - name: Send Slack Notification
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE_FILE: slack_msg.txt